### ISSUE TITLE
‘Issue: Failed to add edge detection’

### ISSUE THREAD

**Issue by iiqqrs** [veebch/btcticker#92] opened 2021-11-14 22:48 UTC
At very random times the ticker decides to fail and stare ‘issue: failed to add edge detection Line 521’ 
I simply kill the power and boot it up and it’s back to normal (for some time) and then a few hours… days… it happens again.
![FFC32BEC-A30B-488C-8BF2-20D9F003ACC4](https://user-images.githubusercontent.com/17475989/141701751-851f977f-fab3-488e-b53e-ea5495f9131f.jpeg)

**Comment by llvllch** [comment] 2021-11-15 07:50
I've seen this one but couldn't reproduce it. A quick google made me think it might be a GPIO thing. I'll look into it.

**Comment by neilneil2000** [comment] 2022-01-22 19:27
I forked your project and switched to gpiozero. It seems simpler and more stable than RPi.gpio

**Comment by veebch** [comment] 2022-01-23 12:53
I just glanced at your changes, looks like you have really tidied things up!

**Comment by neilneil2000** [comment] 2022-01-23 22:17
I’ve been teaching myself Python and using it as a little project to hone my skills!

**Comment by veebch** [comment] 2022-01-24 07:57
Great success :)
Closing this issue.... I will look at your code properly and see if I can pick up some good tips!

**Closed by veebch** 2022-01-24 07:57 UTC
